### ISSUE TITLE
Bug: Body spawns under random players

### ISSUE THREAD

**Issue by mexikoedi** [TTT-2/ttt2-wep_boom_body#1]
The boom body spawns under random players after the placement.
Here a video: https://sendvid.com/hb0ycm4k (Needs to load a bit.)

**Comment by TimGoll** [comment]
are you sure? I'm pretty sure I already fixed this in the last update

**Comment by mexikoedi** [comment]
I played some rounds today and noticed it. Then I tried it locally with bots and recorded the video. 
I saw that you fixed it but somehow they still spawn random. Not in the world random but under random players. 
Not sure if it is an issue on my end (local and public sever) or not... if yes then I don't know why.
